package reschu.userinput;

import java.util.*;

/** 
 * Custom event class MUST extend AWTEvent or EventObject.
 * Normally you extend AWTEvent for events generated by a graphical component
 * and EventObject any other time.
 * 
 * @author yale 
 */
public class UserInputEvent extends EventObject {
 
	private static final long serialVersionUID = 3518374394018575783L; 
	
	// variables
	private int _time;
	private int _invoker;
	private int _type;
	private String _log;
	private int _mouseCoordX;
	private int _mouseCoordY;

	public UserInputEvent(Object source, int time, int invoker, int type, String log, int mouseCoordX, int mouseCoordY) {
		super(source);
		_time = time;
		_invoker = invoker;
		_type = type;
		_log = log;
		_mouseCoordX = mouseCoordX;
		_mouseCoordY = mouseCoordY;
	}
	
	public int getTime() { return _time; }
	public int getInvoker() { return _invoker; }
	public int getType() { return _type; }
	public String getLog() { return _log; }
	public int getMouseCoordX() { return _mouseCoordX; }
	public int getMouseCoordY() { return _mouseCoordY; }	
}
