/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class parport_ParallelPort */

#ifndef _Included_parport_ParallelPort
#define _Included_parport_ParallelPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     parport_ParallelPort
 * Method:    readOneByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_parport_ParallelPort_readOneByte
  (JNIEnv *, jclass, jint);

/*
 * Class:     parport_ParallelPort
 * Method:    writeOneByte
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_parport_ParallelPort_writeOneByte
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
